# Generated by Django 3.1.1 on 2021-03-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategys',
            fields=[
                ('strategy_id', models.AutoField(primary_key=True, serialize=False)),
                ('creator', models.IntegerField()),
                ('strategy_name', models.CharField(max_length=255)),
                ('strategy_details', models.CharField(max_length=255)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('is_share', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'strategys',
                'managed': True,
            },
        ),
    ]
