# Generated by Django 3.1.1 on 2021-03-21 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategys', '0001_initial'),
        ('my', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDetails',
            fields=[
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_id', models.IntegerField()),
                ('strategy_id', models.IntegerField()),
                ('execution_time', models.DateField()),
                ('execution_time_description', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('user_id', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
            options={
                'db_table': 'policy_details',
                'managed': True,
                'unique_together': {('user_id', 'plan_id', 'strategy_id', 'execution_time')},
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=255)),
                ('current_time', models.DateField()),
                ('begin_time', models.DateField()),
                ('end_time', models.DateField()),
                ('status', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.IntegerField()),
                ('plan_type', models.IntegerField(blank=True, null=True)),
                ('strategy_id', models.ForeignKey(blank=True, db_column='strategy_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='strategys.strategys')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.DO_NOTHING, to='my.users')),
            ],
            options={
                'db_table': 'plans',
                'managed': True,
            },
        ),
    ]
